[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Regular Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 1

[window.padding]
x = 20
y = 20

[general]
live_config_reload = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
